version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: /home/ubuntu/before-install.sh
      timeout: 10
  
  Install:
    - location: /home/ubuntu/start.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: /home/ubuntu/check-deployment.sh
      timeout: 10
      runas: ubuntu
