version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 60
      runas: root
  
  Install:
    - location: scripts/start.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/check-deployment.sh
      timeout: 60
      runas: root
