version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  pre_build:
    commands:
      - BUILD_STATUS=""
      #Code Formating
      - npx prettier --write .
      #Code Linting
      - npx eslint --fix .
      #Code Testing
      - npm test
      
      #Stop Container if is still running from previous build
      - CONTAINER_ID=$(docker ps --filter "publish=80" -q)
      - if [ ! -z "$CONTAINER_ID" ]; then docker stop ${CONTAINER_ID}; docker rm ${CONTAINER_ID}; fi


  build:
    commands:

      - BUILD_STATUS="success"
      - echo "Build and analysis completed"

  post_build:
    commands:
      
 
      # Bitte erstell mir hier ein contitional. whenn buildstatus = success, then do the sns
      # Send Build SNS
      - |
      if [ "$BUILD_STATUS" = "success" ]; then
        gh pr create --base main --head dev --title "Testing dev branch successfull" --body "The tests and build of the dev branch got succesfully tested and are ready to be merged into main branch."
        aws sns publish --topic-arn arn:aws:sns:eu-central-1:283919506801:eagler-pipepline --message "Build success for Dev Branch. Pull Request Created"
      else
        echo "Build failed or status unknown, not sending SNS message."
      fi




artifacts:
  files:
    - "**/*"
