version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "install"

  pre_build:
    commands:
      - BUILD_STATUS=""

      
  build:
    commands:
      - echo "Get .env for Docker Image testing"
      

  post_build:
    commands:
      - echo "postbuild"

artifacts:
  files:
    - 'scripts/*'
    - 'appspec.yml'