version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  pre_build:
    commands:
      - BUILD_STATUS=""



  build:
    commands:
      #Get .envs for dockercontainer etc.

      - BUILD_STATUS="success"
      - echo "Build and analysis completed"

  post_build:
    commands:
      - |
        if [ "$BUILD_STATUS" = "success" ]; then
          gh pr create --base main --head dev --title "Testing dev branch successful" --body "The tests and build of the dev branch got successfully tested and are ready to be merged into the main branch."
          aws sns publish --topic-arn arn:aws:sns:eu-central-1:283919506801:eagler-pipepline --message "Build success for Dev Branch. Pull Request Created"
        else
          echo "Build failed or status unknown, not sending SNS message."
        fi



artifacts:
  files:
    - "**/*"
